In [2]:
import pandas as pd

In [4]:
df=pd.read_csv("spam.csv")

In [6]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [8]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [10]:
df["spam"]=df["Category"].apply(lambda x: 1 if x=="spam" else 0)

In [12]:
df.shape

(5572, 3)

In [14]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

Train Test Split


In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.2)

In [22]:
X_train.shape

(4457,)

In [24]:
X_test.shape

(1115,)

In [26]:
#bag of words
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
X_train_cv=v.fit_transform(X_train.values)
X_train_cv

<4457x7785 sparse matrix of type '<class 'numpy.int64'>'
	with 59526 stored elements in Compressed Sparse Row format>

In [28]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [30]:
X_train_np=X_train_cv.toarray()
X_train_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [32]:
#Naive Bais Model
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [34]:
X_test_cv=v.transform(X_test)

Evaluate Performance

In [45]:
from sklearn.metrics import classification_report

y_pred=model.predict(X_test_cv)
print(classification_report(y_test,y_pred))


              precision    recall  f1-score   support

           0       0.99      0.99      0.99       946
           1       0.97      0.94      0.95       169

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [47]:
emails=[
    'Hey mohan , can we get together to watch football game tomorrow',
    'upto 20% discount obn parking ,exclusive offer just for you .Dont miss'
]

emails_count=v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)